// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CorrNormal
arma::mat CorrNormal(const int& n, const arma::mat& corr);
RcppExport SEXP StochasticProcess_CorrNormal(SEXP nSEXP, SEXP corrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type corr(corrSEXP);
    rcpp_result_gen = Rcpp::wrap(CorrNormal(n, corr));
    return rcpp_result_gen;
END_RCPP
}
// BM
arma::cube BM(const double& start, const double& mu, const double& vol, const int& n_dec, const int& n_path, const bool& antithetic);
RcppExport SEXP StochasticProcess_BM(SEXP startSEXP, SEXP muSEXP, SEXP volSEXP, SEXP n_decSEXP, SEXP n_pathSEXP, SEXP antitheticSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_dec(n_decSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_path(n_pathSEXP);
    Rcpp::traits::input_parameter< const bool& >::type antithetic(antitheticSEXP);
    rcpp_result_gen = Rcpp::wrap(BM(start, mu, vol, n_dec, n_path, antithetic));
    return rcpp_result_gen;
END_RCPP
}
// GBM
arma::cube GBM(const double& start, const double& mu, const double& vol, const int& n_dec, const int& n_path, const bool& antithetic);
RcppExport SEXP StochasticProcess_GBM(SEXP startSEXP, SEXP muSEXP, SEXP volSEXP, SEXP n_decSEXP, SEXP n_pathSEXP, SEXP antitheticSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_dec(n_decSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_path(n_pathSEXP);
    Rcpp::traits::input_parameter< const bool& >::type antithetic(antitheticSEXP);
    rcpp_result_gen = Rcpp::wrap(GBM(start, mu, vol, n_dec, n_path, antithetic));
    return rcpp_result_gen;
END_RCPP
}
// CBM
arma::cube CBM(const arma::vec& start, const arma::vec& mu, const arma::vec& vol, const arma::mat& corr, const int& n_dec, const int& n_path, const bool& antithetic);
RcppExport SEXP StochasticProcess_CBM(SEXP startSEXP, SEXP muSEXP, SEXP volSEXP, SEXP corrSEXP, SEXP n_decSEXP, SEXP n_pathSEXP, SEXP antitheticSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type corr(corrSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_dec(n_decSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_path(n_pathSEXP);
    Rcpp::traits::input_parameter< const bool& >::type antithetic(antitheticSEXP);
    rcpp_result_gen = Rcpp::wrap(CBM(start, mu, vol, corr, n_dec, n_path, antithetic));
    return rcpp_result_gen;
END_RCPP
}
// CGBM
arma::cube CGBM(const arma::vec& start, const arma::vec& mu, const arma::vec& vol, const arma::mat& corr, const int& n_dec, const int& n_path, const bool& antithetic);
RcppExport SEXP StochasticProcess_CGBM(SEXP startSEXP, SEXP muSEXP, SEXP volSEXP, SEXP corrSEXP, SEXP n_decSEXP, SEXP n_pathSEXP, SEXP antitheticSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type corr(corrSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_dec(n_decSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_path(n_pathSEXP);
    Rcpp::traits::input_parameter< const bool& >::type antithetic(antitheticSEXP);
    rcpp_result_gen = Rcpp::wrap(CGBM(start, mu, vol, corr, n_dec, n_path, antithetic));
    return rcpp_result_gen;
END_RCPP
}
// NestedBM
arma::cube NestedBM(const arma::cube& path, const double& mu, const double& vol, const int& n_subsim, const bool& antithetic);
RcppExport SEXP StochasticProcess_NestedBM(SEXP pathSEXP, SEXP muSEXP, SEXP volSEXP, SEXP n_subsimSEXP, SEXP antitheticSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_subsim(n_subsimSEXP);
    Rcpp::traits::input_parameter< const bool& >::type antithetic(antitheticSEXP);
    rcpp_result_gen = Rcpp::wrap(NestedBM(path, mu, vol, n_subsim, antithetic));
    return rcpp_result_gen;
END_RCPP
}
// NestedGBM
arma::cube NestedGBM(const arma::cube& path, const double& mu, const double& vol, const int& n_subsim, const bool& antithetic);
RcppExport SEXP StochasticProcess_NestedGBM(SEXP pathSEXP, SEXP muSEXP, SEXP volSEXP, SEXP n_subsimSEXP, SEXP antitheticSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_subsim(n_subsimSEXP);
    Rcpp::traits::input_parameter< const bool& >::type antithetic(antitheticSEXP);
    rcpp_result_gen = Rcpp::wrap(NestedGBM(path, mu, vol, n_subsim, antithetic));
    return rcpp_result_gen;
END_RCPP
}
// NestedCBM
arma::cube NestedCBM(const arma::cube& path, const arma::vec& mu, const arma::vec& vol, const arma::mat& corr, const int& n_subsim, const bool& antithetic);
RcppExport SEXP StochasticProcess_NestedCBM(SEXP pathSEXP, SEXP muSEXP, SEXP volSEXP, SEXP corrSEXP, SEXP n_subsimSEXP, SEXP antitheticSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type corr(corrSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_subsim(n_subsimSEXP);
    Rcpp::traits::input_parameter< const bool& >::type antithetic(antitheticSEXP);
    rcpp_result_gen = Rcpp::wrap(NestedCBM(path, mu, vol, corr, n_subsim, antithetic));
    return rcpp_result_gen;
END_RCPP
}
// NestedCGBM
arma::cube NestedCGBM(const arma::cube& path, const arma::vec& mu, const arma::vec& vol, const arma::mat& corr, const int& n_subsim, const bool& antithetic);
RcppExport SEXP StochasticProcess_NestedCGBM(SEXP pathSEXP, SEXP muSEXP, SEXP volSEXP, SEXP corrSEXP, SEXP n_subsimSEXP, SEXP antitheticSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vol(volSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type corr(corrSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_subsim(n_subsimSEXP);
    Rcpp::traits::input_parameter< const bool& >::type antithetic(antitheticSEXP);
    rcpp_result_gen = Rcpp::wrap(NestedCGBM(path, mu, vol, corr, n_subsim, antithetic));
    return rcpp_result_gen;
END_RCPP
}
